name: Main Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  pr-check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: node setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Installing html validator
        run: npm i -g html-validate

      - name: Check  validation of ornek.html
        run: html-validate ornek.html